apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-flow-prod
resources:
  - namespace.yaml
  - ../../base/namespaced
patches:
  - target:
      kind: ResourceQuota
      name: pod-count-quota
    patch: |-
      - op: replace
        path: /spec/hard/pods
        value: "1"
