apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo-config
  namespace: configmap-rotations
data:
  application.yaml: |
    server:
      port: 8080

    feature:
      enabled: false

    management:
      endpoints:
        web:
          exposure:
            include: health,info
